### ISSUE TITLE
     // Assert     Assert.assertFalse(Util.areEqual(encryptedData, decryptedData));     Assert.assertTrue(Util.areEqual(data, decryptedData));   }

### ISSUE THREAD

**Issue by Karol-Madnet** [SoftwareVerde/java-cryptography#1]
https://github.com/SoftwareVerde/java-cryptography/blob/27b3c08e618814d47049c6522e896529d82095af/src/test/java/com/softwareverde/cryptography/aes/AesKeyTests.java#L30

**Comment by Karol-Madnet** [comment]
[gcloud-cheat-sheet (1).pdf](https://github.com/SoftwareVerde/java-cryptography/files/11153456/gcloud-cheat-sheet.1.pdf)

**Comment by joshmg** [comment]
Closing for spam.
